<?php
$senha = '987794585';
echo $password = md5($senha);

$data = '2018-01-22 21:01:00';

//$email = 'fabio.bonina@gruposabara.com';
//echo $avatar = "http://www.gravatar.com/avatar/".md5($email)."?d=identicon";
//echo date("d-m-Y", $data);
// Explode a barra e retorna três arrays
//$data = explode("-", $data);
//echo date('d/m/Y', strtotime(str_replace('-','/', $data)));
// Cria três variáveis $ano $mes $dia
//echo list($dia, $mes, $ano) = $data;

//echo $DateOfRequest = date("d/m/Y H:i:s", strtotime($data));

SERVICO AUTONOMO DE AGUA E ESGOTO - BOA VIAGEM
SERVICO AUTONOMO DE AGUA E ESGOTO - MARECHAL DEODORO
SERVICO AUTONOMO DE AGUA E ESGOTO - PALMARES
SERVICO AUTONOMO DE AGUA E ESGOTO - PENEDO
SERVICO AUTONOMO DE AGUA E ESGOTO - SAO MIGUEL CAMPOS
SERVICO AUTONOMO DE AGUA E ESGOTO - UNIAO DOS PALMARES
SERVICO AUTONOMO DE AGUA E ESGOTO - VICOSA
SERVICO AUTONOMO DE AGUA E ESGOTO - JAGUARIBE
SABARA QUIMICOS E INGREDIENTES S A
SERVICO AUTONOMO DE AGUA E ESGOTO - ITAPIPOCA
SERVICO AUTONOMO DE AGUA E ESGOTO - QUIXERAMOBIM
SERVICO AUTONOMO DE AGUA E ESGOTO - MORADA NOVA
SERVICO AUTONOMO DE AGUA E ESGOTO - ATALAIA
SERVICO AUTONOMO DE AGUA E ESGOTO - AGUA PRETA
SERVICO AUTONOMO DE AGUA E ESGOTO - ALAGOINHA
SERVICO AUTONOMO DE AGUA E ESGOTO - AMARAJI
SERVICO AUTONOMO DE AGUA E ESGOTO - BOA VIAGEM
SERVICO AUTONOMO DE AGUA E ESGOTO - BOCA DA MATA
SERVICO AUTONOMO DE AGUA E ESGOTO - CAJUEIRO
SERVICO AUTONOMO DE AGUA E ESGOTO - IGUATU
SERVICO AUTONOMO DE AGUA E ESGOTO - LIMOEIRO DO NORTE
SERVICO AUTONOMO DE AGUA E ESGOTO - PEDRA BRANCA
SERVICO AUTONOMO DE AGUA E ESGOTO - SOBRAL



