-- MySQL Script generated by MySQL Workbench
-- 10/02/16 06:21:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema system_tec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema system_tec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system_tec` DEFAULT CHARACTER SET utf8 ;
USE `system_tec` ;

-- -----------------------------------------------------
-- Table `system_tec`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`login` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nickuser` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nivel` ENUM('0', '1') NOT NULL DEFAULT '0',
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  `data_cadastro` DATE NOT NULL DEFAULT '0000-00-00',
  `data_ultimo_login` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `niciuser_UNIQUE` (`nickuser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_clientes` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nick` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_localidades` (
  `id` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `regional` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `latitude` FLOAT(10,6) NULL DEFAULT NULL,
  `longitude` FLOAT(10,6) NULL DEFAULT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_localidades_tb_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_tb_localidades_tb_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `system_tec`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_servicos` (
  `id` VARCHAR(6) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_sistema` (
  `id` VARCHAR(10) NOT NULL,
  `descrico` VARCHAR(45) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_oat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_oat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nickuser` VARCHAR(30) NOT NULL,
  `tb_clientes_id` INT(11) NOT NULL,
  `tb_localidades_id` INT(11) NOT NULL,
  `tb_servicos_id` VARCHAR(6) NOT NULL,
  `tb_sistema_id` VARCHAR(10) NOT NULL,
  `data_sol` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `filial` INT(2) NULL DEFAULT NULL,
  `os` INT(11) NULL DEFAULT NULL,
  `data_os` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `data_fech` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `data_term` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `status` ENUM('0', '1', '2', '3') NOT NULL DEFAULT '0',
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_oat_tb_clientes1_idx` (`tb_clientes_id` ASC),
  INDEX `fk_tb_oat_tb_localidades1_idx` (`tb_localidades_id` ASC),
  INDEX `fk_tb_oat_tb_servicos1_idx` (`tb_servicos_id` ASC),
  INDEX `fk_tb_oat_tb_sistema1_idx` (`tb_sistema_id` ASC),
  INDEX `nuckuser_idx` (`nickuser` ASC),
  CONSTRAINT `fk_tb_oat_tb_clientes1`
    FOREIGN KEY (`tb_clientes_id`)
    REFERENCES `system_tec`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_oat_tb_localidades1`
    FOREIGN KEY (`tb_localidades_id`)
    REFERENCES `system_tec`.`tb_localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_oat_tb_servicos1`
    FOREIGN KEY (`tb_servicos_id`)
    REFERENCES `system_tec`.`tb_servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_oat_tb_sistema1`
    FOREIGN KEY (`tb_sistema_id`)
    REFERENCES `system_tec`.`tb_sistema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nuckuser`
    FOREIGN KEY (`nickuser`)
    REFERENCES `system_tec`.`login` (`nickuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_ativo` (
  `id` INT(11) NOT NULL,
  `tb_oat_id` INT(11) NOT NULL,
  `plaqueta` INT(11) NOT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_ativo_tb_oat1_idx` (`tb_oat_id` ASC),
  CONSTRAINT `fk_tb_ativo_tb_oat1`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `system_tec`.`tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_tecnicos` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nick_user` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nickuser_idx` (`nick_user` ASC),
  CONSTRAINT `nickuser`
    FOREIGN KEY (`nick_user`)
    REFERENCES `system_tec`.`login` (`nickuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_mod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_mod` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicial` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `data_final` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `tb_tecnicos_id` INT(11) NOT NULL,
  `tb_oat_id` INT(11) NOT NULL,
  INDEX `fk_tb_mod_tb_tecnicos1_idx` (`tb_tecnicos_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_tb_mod_tb_oat1_idx` (`tb_oat_id` ASC),
  CONSTRAINT `fk_tb_mod_tb_tecnicos1`
    FOREIGN KEY (`tb_tecnicos_id`)
    REFERENCES `system_tec`.`tb_tecnicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mod_tb_oat1`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `system_tec`.`tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tipo_despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tipo_despesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_despesa` VARCHAR(45) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_osdespesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_osdespesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tb_oat_id` INT(11) NOT NULL,
  `tipo_despesa_id` INT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_osdespesa_tb_oat1_idx` (`tb_oat_id` ASC),
  INDEX `fk_tb_osdespesa_tipo_despesa1_idx` (`tipo_despesa_id` ASC),
  CONSTRAINT `fk_tb_osdespesa_tb_oat1`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `system_tec`.`tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_osdespesa_tipo_despesa1`
    FOREIGN KEY (`tipo_despesa_id`)
    REFERENCES `system_tec`.`tipo_despesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_postagens` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `data` VARCHAR(12) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `exibir` VARCHAR(5) NOT NULL,
  `descricao` LONGTEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `system_tec`.`tb_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_tec`.`tb_insumos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tb_oat_id` INT(11) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `obs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_osdespesa_tb_oat1_idx` (`tb_oat_id` ASC),
  CONSTRAINT `fk_tb_osdespesa_tb_oat10`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `system_tec`.`tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
