-- MySQL Script generated by MySQL Workbench
-- 10/31/16 06:17:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system_tec` DEFAULT CHARACTER SET latin1 ;
USE `system_tec` ;

-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nickuser` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nivel` ENUM('0', '1', '2', '3') NOT NULL DEFAULT '0',
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  `data_cadastro` DATE NOT NULL DEFAULT '0000-00-00',
  `data_ultimo_login` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `niciuser_UNIQUE` (`nickuser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_clientes` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nick` VARCHAR(30) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nick` (`nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_localidades` (
  `id` INT(11) NOT NULL,
  `cliente` VARCHAR(30) NOT NULL,
  `regional` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `latitude` FLOAT(10,6) NULL DEFAULT NULL,
  `longitude` FLOAT(10,6) NULL DEFAULT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_clientes` (`cliente` ASC),
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `tb_clientes` (`nick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_ativo` (
  `id` INT(11) NOT NULL,
  `cliente` VARCHAR(30) NOT NULL,
  `localidade` INT(11) NOT NULL,
  `plaqueta` VARCHAR(11) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  INDEX `fk_cliente` (`cliente` ASC),
  INDEX `fk_localidade` (`localidade` ASC),
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `tb_clientes` (`nick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localidade`
    FOREIGN KEY (`localidade`)
    REFERENCES `tb_localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_servicos` (
  `id` VARCHAR(6) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_sistema` (
  `id` VARCHAR(12) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_oat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_oat` (
  `id` INT(11) NOT NULL,
  `nickuser` VARCHAR(30) NOT NULL,
  `cliente` VARCHAR(30) NOT NULL,
  `localidade` INT(11) NOT NULL,
  `servico` VARCHAR(6) NOT NULL,
  `sistema` VARCHAR(12) NOT NULL,
  `data_sol` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `filial` INT(2) NULL DEFAULT NULL,
  `os` INT(11) NULL DEFAULT NULL,
  `data_os` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `data_fech` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `data_term` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `status` ENUM('0', '1', '2', '3') NOT NULL DEFAULT '0',
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_localidade` (`localidade` ASC),
  INDEX `fk_servico` (`servico` ASC),
  INDEX `fk_sistema` (`sistema` ASC),
  INDEX `fk_nuckuser` (`nickuser` ASC),
  CONSTRAINT `nickuser`
    FOREIGN KEY (`nickuser`)
    REFERENCES `login` (`nickuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `tb_clientes` (`nick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localidade`
    FOREIGN KEY (`localidade`)
    REFERENCES `tb_localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servico`
    FOREIGN KEY (`servico`)
    REFERENCES `tb_servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sistema`
    FOREIGN KEY (`sistema`)
    REFERENCES `tb_sistema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_descricao` (
  `id` INT(11) NOT NULL,
  `oat` INT(11) NOT NULL,
  `descricao` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tb_oat` (`oat` ASC),
  CONSTRAINT `oat`
    FOREIGN KEY (`oat`)
    REFERENCES `tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_insumos` (
  `id` INT(11) NOT NULL,
  `tb_oat_id` INT(11) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `obs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tb_osdespesa_tb_oat10`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_tecnicos` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nick_user` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `nickuser`
    FOREIGN KEY (`nick_user`)
    REFERENCES `login` (`nickuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_mod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_mod` (
  `id` INT(11) NOT NULL,
  `data_inicial` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `data_final` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `tb_tecnicos_id` INT(11) NOT NULL,
  `tb_oat_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_mod_tb_tecnicos1_idx` (`tb_tecnicos_id` ASC),
  INDEX `fk_tb_mod_tb_oat1_idx` (`tb_oat_id` ASC),
  CONSTRAINT `fk_tb_mod_tb_oat1`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mod_tb_tecnicos1`
    FOREIGN KEY (`tb_tecnicos_id`)
    REFERENCES `tb_tecnicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tipo_despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_despesa` (
  `id` INT(11) NOT NULL,
  `tipo_despesa` VARCHAR(45) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_osdespesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_osdespesa` (
  `id` INT(11) NOT NULL,
  `tb_oat_id` INT(11) NOT NULL,
  `tipo_despesa_id` INT(11) NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_osdespesa_tb_oat1_idx` (`tb_oat_id` ASC),
  INDEX `fk_tb_osdespesa_tipo_despesa1_idx` (`tipo_despesa_id` ASC),
  CONSTRAINT `fk_tb_osdespesa_tb_oat1`
    FOREIGN KEY (`tb_oat_id`)
    REFERENCES `tb_oat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_osdespesa_tipo_despesa1`
    FOREIGN KEY (`tipo_despesa_id`)
    REFERENCES `tipo_despesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_postagens` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `data` VARCHAR(12) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `exibir` VARCHAR(5) NOT NULL,
  `descricao` LONGTEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
